#!/usr/bin/env python3
import json
import re

# 전체 번역 매핑
translations = {
    # 기존 번역
    "Replit for Enterprise": "Replit 기업용",
    "End your engineering backlog, empower non-technical teams and build ideas that would normally be lost": "엔지니어링 백로그를 끝내고, 비기술 팀에 권한을 부여하며 일반적으로 잃어버릴 아이디어를 구축하세요",
    "The Enterprise Impact": "기업 영향력",
    "Only 20% of an organization can make software to solve problems for the rest of the company. People don't even think in terms of \"how could I solve this problem myself\" because it hasn't been possible.": "조직의 20%만이 회사의 나머지를 위한 문제를 해결하는 소프트웨어를 만들 수 있습니다. 사람들은 '내가 이 문제를 직접 어떻게 해결할 수 있을까'라는 관점에서 생각조차 하지 않습니다. 불가능했기 때문입니다.",
    "What Does This Constraint Actually Cost?": "이 제약 조건의 실제 비용은 얼마입니까?",
    "It's hard to see the cost of something that's always been there. But when only engineers can build software, every company pays an invisible tax": "항상 존재했던 것의 비용을 보기는 어렵습니다. 하지만 엔지니어만 소프트웨어를 구축할 수 있을 때, 모든 회사는 보이지 않는 세금을 지불합니다",
    "Quarterly SDLC": "분기별 SDLC",
    "Time from customer to proof of concept (POC) can take weeks of iteration with engineering.": "고객으로부터 개념 증명(POC)까지의 시간은 엔지니어링과 함께 몇 주간의 반복 작업이 걸릴 수 있습니다.",
    "delays on product launch timelines": "제품 출시 일정 지연",
    "Expensive SaaS": "비싼 SaaS",
    "Generic solutions tools can cost a lot, and they often have unused features or limitations.": "일반적인 솔루션 도구는 비용이 많이 들 수 있으며, 사용하지 않는 기능이나 제한 사항이 있는 경우가 많습니다.",
    "in SaaS spend per employee": "직원당 SaaS 지출",
    "Lost Ideas": "잃어버린 아이디어",
    "Thousands of ideas or productivity tools never happen because of limited eng resources.": "수천 개의 아이디어나 생산성 도구가 제한된 엔지니어링 리소스로 인해 실현되지 못합니다.",
    "in revenue spent on R&D, primarily engineering": "매출 대비 R&D 지출, 주로 엔지니어링",
    "Sources: 1. Supply & Demand Chain; 2. Moody's; 3. Spendesk": "출처: 1. Supply & Demand Chain; 2. Moody's; 3. Spendesk",
    "The Hidden Cost": "숨겨진 비용",
    "The most important impact is the hardest to quantify—the thousands of ideas that never see the light of day.": "가장 중요한 영향은 수량화하기 가장 어렵습니다—빛을 보지 못하는 수천 개의 아이디어입니다.",
    "idea to application can take years at companies...": "아이디어에서 애플리케이션까지 기업에서 수년이 걸릴 수 있습니다...",
    "But with Replit, it's accelerated.": "하지만 Replit을 사용하면 가속화됩니다.",
    "How does Replit change things?": "Replit은 어떻게 변화를 가져오나요?",
    "Empowering the other 80% to build.": "나머지 80%가 구축할 수 있도록 권한을 부여합니다.",
    "The five month journey of Zillow": "Zillow의 5개월 여정",
    "From one employee to org-wide transformation in months": "한 명의 직원에서 몇 달 만에 조직 전체의 변혁으로",
    "Builds first app": "첫 앱 구축",
    "Mike Messenger (Product Manager) makes an app to route local real estate leads": "Mike Messenger(제품 관리자)가 지역 부동산 리드를 라우팅하는 앱을 만듭니다",
    "Drives +$10M": "천만 달러 이상 창출",
    "The application drives higher conversion, leading to tens of millions in value for the business.": "애플리케이션은 더 높은 전환을 이끌어 비즈니스에 수천만 달러의 가치를 제공합니다.",
    "Formal pilot + hackathon": "공식 파일럿 + 해커톤",
    "Product leadership decides to test scaling the tool with the org.": "제품 리더십이 조직과 함께 도구를 확장하는 테스트를 결정합니다.",
    "+500 seats": "+500석",
    "Replit is widely adopted across product, design, and operations. Zillow deploys +200 apps hosted on Replit.": "Replit은 제품, 디자인 및 운영 전반에 걸쳐 널리 채택되었습니다. Zillow는 Replit에서 호스팅되는 200개 이상의 앱을 배포합니다.",
    "Transforming the org": "조직 변혁",
    "The PDLC is being rearchitected. Product and design organizations are now requiring Replit prototypes before engaging engineering.": "PDLC가 재설계되고 있습니다. 제품 및 디자인 조직은 이제 엔지니어링에 참여하기 전에 Replit 프로토타입을 요구합니다.",
    "Trusted by Leading Enterprises": "선도 기업들이 신뢰하는",
    "Join the world's most innovative companies using Replit": "Replit을 사용하는 세계에서 가장 혁신적인 기업에 합류하세요",
    "Case Study: WHOOP": "사례 연구: WHOOP",
    "Accelerating Validation with Replit": "Replit을 통한 검증 가속화",
    "Case Study: Rokt": "사례 연구: Rokt",
    "What began as one app quickly became an organization-wide transformation": "하나의 앱으로 시작한 것이 빠르게 조직 전체의 변혁이 되었습니다",
    "Privacy, Security & Governance Controls": "개인 정보 보호, 보안 및 거버넌스 제어",
    "Enterprise-grade security at every layer": "모든 계층에서 엔터프라이즈급 보안",
    "Production Deployment Capabilities": "프로덕션 배포 기능",
    "Replit is on Google Cloud & Azure Marketplace": "Replit은 Google Cloud 및 Azure Marketplace에 있습니다",
    "Use your cloud commit to bring Replit into your team": "클라우드 커밋을 사용하여 Replit을 팀에 도입하세요",
    "Figma MCP Integration": "Figma MCP 통합",
    "Connect Agent to your Figma files via MCP to explore layers, extract design data, capture screenshots, and generate starter code from designs.": "MCP를 통해 에이전트를 Figma 파일에 연결하여 레이어를 탐색하고, 디자인 데이터를 추출하고, 스크린샷을 캡처하고, 디자인에서 시작 코드를 생성합니다.",
    "Figma MCP Demo": "Figma MCP 데모",
    "Watch how designs become working apps instantly": "디자인이 즉시 작동하는 앱이 되는 것을 확인하세요",
    "Connectors": "커넥터",
    "Build with your real data": "실제 데이터로 구축하세요",
    "What will you build?": "무엇을 구축하시겠습니까?",
    "Whether you're prototyping or launching production-ready apps, Replit lets you securely vibe code with your team—with database, auth, and deployment built in.": "프로토타입을 만들거나 프로덕션 준비가 된 앱을 출시하든, Replit을 사용하면 데이터베이스, 인증 및 배포가 내장된 상태로 팀과 안전하게 코드를 작성할 수 있습니다.",
    "Start building": "구축 시작",
    
    # 추가 번역 (누락된 항목들)
    "Start Building": "구축 시작",
    "Start building ": "구축 시작 ",
    "WHOOP's product team had 150+ ideas they needed built and tested so they could validate which ones were worth pursuing further.": "WHOOP의 제품 팀은 150개 이상의 아이디어를 구축하고 테스트하여 어떤 것을 더 추구할 가치가 있는지 검증해야 했습니다.",
    "The Challenge:": "과제:",
    "Overwhelmed & capacity-constrained": "압도당하고 용량 제약",
    "Only engineers can create software": "엔지니어만 소프트웨어를 만들 수 있습니다",
    "Capacity Bottleneck": "용량 병목",
    "WAITING ON ENG": "엔지니어링 대기 중",
    "Discovering Replit": "Replit 발견",
    "Bottlenecked by engineering, they imported their Figma designs directly into Replit and built all the ideas themselves in 24 hours.": "엔지니어링에 병목되어, 그들은 Figma 디자인을 Replit으로 직접 가져와서 24시간 만에 모든 아이디어를 직접 구축했습니다.",
    "Apps built in 24 hours": "24시간 만에 구축된 앱",
    "App Testing & Validation": "앱 테스트 및 검증",
    "They were then able to test and validate these ideas internally.": "그들은 이러한 아이디어를 내부적으로 테스트하고 검증할 수 있었습니다.",
    "Through validation, they found that only 8 ideas should be pursued further. Not only were they reducing their ask of engineering (and thus reducing the backlog), but they were also handing off working code, which shortened their PDLC even further.": "검증을 통해 8개의 아이디어만 더 추구해야 한다는 것을 발견했습니다. 엔지니어링에 대한 요청을 줄일 뿐만 아니라(따라서 백로그 감소), 작동하는 코드를 넘겨주어 PDLC를 더욱 단축시켰습니다.",
    "The Innovation Bottleneck": "혁신 병목",
    "In recent decades - almost all the noticeable innovation has been driven by software. And that innovation has been the exclusive purview of a tiny percent of the population - engineers.": "최근 수십 년 동안 거의 모든 눈에 띄는 혁신은 소프트웨어에 의해 주도되었습니다. 그리고 그 혁신은 인구의 작은 비율인 엔지니어의 독점 영역이었습니다.",
    "Software is Innovation": "소프트웨어는 혁신입니다",
    "We don't even notice the constraint": "우리는 제약을 눈치채지도 못합니다",
    "We're so used to that world, we can't even imagine what it would be like to live in one where instead, anyone can create software — and what the implications of that would be.": "우리는 그 세계에 너무 익숙해서, 대신 누구나 소프트웨어를 만들 수 있는 세계에 사는 것이 어떨지, 그것의 의미가 무엇인지 상상조차 할 수 없습니다.",
    "Everyone has ideas": "모두가 아이디어를 가지고 있습니다",
    "The Rokt'athon": "Rokt'athon",
    "Realizing the potential, Rokt empowered all employees to use Replit in a worldwide internal hackathon": "잠재력을 깨닫고, Rokt는 전 세계 내부 해커톤에서 모든 직원이 Replit을 사용할 수 있도록 권한을 부여했습니다",
    "Employees participated globally": "전 세계적으로 직원들이 참여했습니다",
    "Ideas Generated": "생성된 아이디어",
    "Innovations Built": "구축된 혁신",
    "With AI becoming ubiquitous, Rokt knew they would need to operate 5X faster to continue to accelerate its business. To do this, they identified key areas of friction in the business, such as hiring, democratizing analytics and knowledge, friction between their core systems of record and more. ": "AI가 보편화되면서, Rokt는 비즈니스를 계속 가속화하기 위해 5배 더 빠르게 운영해야 한다는 것을 알았습니다. 이를 위해 채용, 분석 및 지식의 민주화, 핵심 기록 시스템 간의 마찰 등 비즈니스의 주요 마찰 영역을 식별했습니다.",
    "Remove all friction that prevented them from operating 5x faster": "5배 더 빠르게 운영하는 것을 방해하는 모든 마찰 제거",
    "Enterprise Adoption": "기업 채택",
    "Replit became one of the": "Replit은 다음 중 하나가 되었습니다",
    "Every department transformed their operations with Replit-built internal tools.": "모든 부서가 Replit으로 구축된 내부 도구로 운영을 변혁했습니다.",
    "Customer Success": "고객 성공",
    "Custom CRM tools, LinkedIn integrations, and communication analyzers.": "맞춤형 CRM 도구, LinkedIn 통합 및 커뮤니케이션 분석기.",
    "Go-to-Market": "시장 진출",
    "Integrated dashboards combining Slack, internal data, and AWS alerts for anomaly detection.": "이상 감지를 위한 Slack, 내부 데이터 및 AWS 알림을 결합한 통합 대시보드.",
    "Operations & Finance": "운영 및 재무",
    "Dashboards for operations and financial reporting; task engines managing and prioritizing 30,000+ tasks annually.": "운영 및 재무 보고를 위한 대시보드; 연간 30,000개 이상의 작업을 관리하고 우선순위를 지정하는 작업 엔진.",
    "Engineering": "엔지니어링",
    "Automated workflow systems, document management, and redlining tools.": "자동화된 워크플로 시스템, 문서 관리 및 수정 도구.",
    "Hover over teams to read stories": "팀 위에 마우스를 올려 스토리를 읽으세요",
    "Customer Pain": "고객 고충",
    "A combination of CRM tools created bottlenecks": "CRM 도구의 조합으로 병목 현상 발생",
    "Each handoff introduces noise. By the time the solution is built, it often solves a different problem than the one the customer has.": "각 인수인계는 노이즈를 도입합니다. 솔루션이 구축될 때쯤이면 고객이 가진 문제와 다른 문제를 해결하는 경우가 많습니다.",
    "Ideas & Solutions": "아이디어 및 솔루션",
    "I built custom portals for our customers with the exact resources they need, plus the health dashboards we always wanted that are actually connected to real data.": "고객에게 필요한 정확한 리소스로 맞춤형 포털을 구축했으며, 실제 데이터에 연결된 우리가 항상 원했던 상태 대시보드도 포함했습니다.",
    "Design Systems": "디자인 시스템",
    "Friction in scaling teams due to siloed knowledge": "사일로화된 지식으로 인한 팀 확장의 마찰",
    "Every design is great until it's used by a user.": "모든 디자인은 사용자가 사용하기 전까지는 훌륭합니다.",
    "I'm building and validating prototypes myself, so we only ask engineering to build things we know will actually make it to production.": "내가 직접 프로토타입을 구축하고 검증하므로, 실제로 프로덕션에 도달할 것을 알고 있는 것만 엔지니어링에 요청합니다.",
    "Figma Backlog": "Figma 백로그",
    "End-of-year close was a tedious, manual process": "연말 마감은 지루하고 수동적인 프로세스였습니다",
    "Our month-end close is now automated with custom reporting that matches our actual chart of accounts and business logic.": "월말 마감은 이제 실제 계정 차트 및 비즈니스 로직과 일치하는 맞춤형 보고로 자동화되었습니다.",
    "Our reps have personal apps connected to their email, calendar, and CRM—one place to do everything, so they spend more time selling.": "우리 담당자는 이메일, 캘린더 및 CRM에 연결된 개인 앱을 가지고 있어 모든 것을 한 곳에서 수행하므로 판매에 더 많은 시간을 할애합니다.",
    "I can build an HCM that's tailored to how our business actually works, not force our processes into someone else's rigid system.": "우리 비즈니스가 실제로 작동하는 방식에 맞춘 HCM을 구축할 수 있으며, 다른 사람의 경직된 시스템에 우리 프로세스를 강제로 맞추지 않습니다.",
    "I'm spinning up internal tools that connect our systems in hours instead of waiting quarters for engineering resources or buying another SaaS product.": "엔지니어링 리소스를 몇 분기 동안 기다리거나 다른 SaaS 제품을 구매하는 대신 몇 시간 만에 시스템을 연결하는 내부 도구를 가동하고 있습니다.",
    "I'm building new landing pages for SEO and product launches myself in minutes—no more waiting on developers or fighting for eng resources.": "SEO 및 제품 출시를 위한 새로운 랜딩 페이지를 몇 분 만에 직접 구축하고 있습니다. 더 이상 개발자를 기다리거나 엔지니어링 리소스를 위해 싸울 필요가 없습니다.",
    "Replit builds front-ends for us—the part we hate doing—and lets us quickly share our work with non-technical product teams without deploying anything.": "Replit은 우리가 싫어하는 부분인 프론트엔드를 구축해주고, 아무것도 배포하지 않고도 비기술 제품 팀과 빠르게 작업을 공유할 수 있게 해줍니다.",
    "I sat there on an iPad mini and deployed a fully functional end-to-end application with OAuth in about a day. And I have no background in engineering.": "iPad mini에서 OAuth를 사용하여 완전히 작동하는 엔드투엔드 애플리케이션을 하루 만에 배포했습니다. 그리고 나는 엔지니어링 배경이 전혀 없습니다.",
    "Privacy, security & governance": "개인 정보 보호, 보안 및 거버넌스",
    "SOC2 Type II Compliant": "SOC2 Type II 준수",
    "Click here to request access to our Trust Center": "여기를 클릭하여 Trust Center에 대한 액세스를 요청하세요",
    "Private Deployments": "프라이빗 배포",
    "Deploy internal tools behind your SSO, isolate workloads in your own VPC or run Replit Agent with your on-premise infrastructure. ": "SSO 뒤에 내부 도구를 배포하거나, 자체 VPC에서 워크로드를 격리하거나, 온프레미스 인프라로 Replit Agent를 실행하세요.",
    "Security & Compliance": "보안 및 규정 준수",
    "Security Center": "보안 센터",
    "Semgrep Integration": "Semgrep 통합",
    "Replit Agent can run a Semgrep scan to automatically find security issues via a curated set of Python, Javascript, and Typescript rules.": "Replit Agent는 Python, Javascript 및 Typescript 규칙의 큐레이션된 세트를 통해 보안 문제를 자동으로 찾기 위해 Semgrep 스캔을 실행할 수 있습니다.",
    "HoundDog Integration": "HoundDog 통합",
    "HoundDog is now integrated into the Security Scanner. It automatically detects sensitive data exposure including PII, API keys, and credentials that could leak through logs or external services.": "HoundDog은 이제 보안 스캐너에 통합되었습니다. 로그나 외부 서비스를 통해 유출될 수 있는 PII, API 키 및 자격 증명을 포함한 민감한 데이터 노출을 자동으로 감지합니다.",
    "CVE Detection": "CVE 감지",
    "SBOM Downloads": "SBOM 다운로드",
    "Visibility & Audit": "가시성 및 감사",
    "Track which apps use which services": "어떤 앱이 어떤 서비스를 사용하는지 추적",
    "Role-Based Access": "역할 기반 액세스",
    "Centralized Management": "중앙 집중식 관리",
    "Admins set up and manage connections once, then make them available to apps across the organization. No more repetitive setup for builders.": "관리자는 연결을 한 번 설정하고 관리한 다음 조직 전체의 앱에서 사용할 수 있도록 합니다. 빌더를 위한 반복 설정이 더 이상 필요하지 않습니다.",
    "Admin setup and approval for organization-wide connections": "조직 전체 연결을 위한 관리자 설정 및 승인",
    "Enforce scoped, least-privilege permissions": "범위가 지정된 최소 권한 권한 적용",
    "Use organization-owned OAuth clients (Enterprise)": "조직 소유 OAuth 클라이언트 사용(엔터프라이즈)",
    "Bring Your Own OAuth": "자체 OAuth 가져오기",
    "Some Available Connectors Include:": "사용 가능한 커넥터 포함:",
    "Connectors let Agent build with your real data": "커넥터를 사용하면 Agent가 실제 데이터로 구축할 수 있습니다",
    "First-party integrations that let Agent build with your real data. Sign in once, reuse connections across all your apps.": "Agent가 실제 데이터로 구축할 수 있는 자사 통합. 한 번 로그인하면 모든 앱에서 연결을 재사용할 수 있습니다.",
    "Example Prompts": "예제 프롬프트",
    "Build a GitHub repository manager using my connected account": "연결된 계정을 사용하여 GitHub 저장소 관리자 구축",
    "Create a Linear task tracker for my team": "팀을 위한 Linear 작업 추적기 생성",
    "Integrate with Outlook to create an email dashboard": "Outlook과 통합하여 이메일 대시보드 생성",
    "Build a Notion-powered website using my Workspace": "내 작업 공간을 사용하여 Notion 기반 웹 사이트 구축",
    "Google Calendar": "Google Calendar",
    "Outlook Calendar": "Outlook Calendar",
    "Google Cloud": "Google Cloud",
    "Microsoft Azure": "Microsoft Azure",
    "American Express": "American Express",
    "Replit Agent": "Replit Agent",
    "Planning Layer (Reasoning & Breakdown)": "계획 레이어(추론 및 분석)",
    "Context Injection": "컨텍스트 주입",
    "Project Files, Docs, User Intent": "프로젝트 파일, 문서, 사용자 의도",
    "Internal API Context": "내부 API 컨텍스트",
    "Execution Engine": "실행 엔진",
    "Code Generation, File Operations, Terminal Commands": "코드 생성, 파일 작업, 터미널 명령",
    "Runtime Verification, Error Recovery, Self-Correction Loops": "런타임 검증, 오류 복구, 자체 수정 루프",
    "Replit Speed": "Replit 속도",
    "Continuous Iteration Loop": "지속적인 반복 루프",
    "Every cycle of the faster loop forces the slower loop to reset its Observe/Orient phase.": "더 빠른 루프의 모든 사이클은 더 느린 루프가 관찰/방향 단계를 재설정하도록 합니다.",
    "Ideas & Solutions": "아이디어 및 솔루션",
    "RE-ORIENTING": "재방향",
    "Reacting...": "반응 중...",
    "Initial kickoff": "초기 시작",
    "Replit Agent Inbox": "Replit Agent 받은 편지함",
    "Needs Review": "검토 필요",
    "Review Agent changes before they merge.": "병합하기 전에 Agent 변경 사항을 검토하세요.",
    "Direct User Testing": "직접 사용자 테스트",
    "Teams can provide feedback asynchronously.": "팀은 비동기적으로 피드백을 제공할 수 있습니다.",
    "Approve & Merge": "승인 및 병합",
    "Version Control": "버전 제어",
    "Context Management": "컨텍스트 관리",
    "Design to code integration": "디자인에서 코드 통합",
    "Figma Import": "Figma 가져오기",
    "Figma / CSS Tokens": "Figma / CSS 토큰",
    "Standardized Boilerplates": "표준화된 보일러플레이트",
    "Custom Templates": "사용자 정의 템플릿",
    "Fully aligned with internal standards, styles, and data.": "내부 표준, 스타일 및 데이터와 완전히 일치합니다.",
    "Additional Resources": "추가 리소스",
    " Async Collaboration": " 비동기 협업",
    " Human-in-the-loop": " 인간 개입",
    "Full app built in 1 day": "1일 만에 구축된 전체 앱",
    "Fix CSS Bug": "CSS 버그 수정",
    "Update Login Flow": "로그인 흐름 업데이트",
    "Compliance App": "규정 준수 앱",
    "Now Google Cloud customers can purchase Replit directly on Google Cloud Marketplace, streamlining procurement and accelerating adoption across the organization.": "이제 Google Cloud 고객은 Google Cloud Marketplace에서 직접 Replit을 구매하여 조달을 간소화하고 조직 전체의 채택을 가속화할 수 있습니다.",
    "Replit's Enterprise customers already have their apps running on Google Cloud's world-class infrastructure, giving every app the security and scalability of Google Cloud.": "Replit의 엔터프라이즈 고객은 이미 Google Cloud의 세계적 수준의 인프라에서 앱을 실행하고 있으며, 모든 앱에 Google Cloud의 보안 및 확장성을 제공합니다.",
    "Replit is integrating with Microsoft infrastructure services including Azure Container Apps, Azure Virtual Machines, and Neon Serverless Postgres.": "Replit은 Azure Container Apps, Azure Virtual Machines 및 Neon Serverless Postgres를 포함한 Microsoft 인프라 서비스와 통합되고 있습니다.",
    "Available on GCP and Azure marketplace": "GCP 및 Azure 마켓플레이스에서 사용 가능",
    "Procurement Options": "조달 옵션",
    "For Organizations": "조직용",
    "Start, Build, Scale model": "시작, 구축, 확장 모델",
    "Auto & Reserved": "자동 및 예약",
    "Enterprise-Grade App": "엔터프라이즈급 앱",
    "Select a section to explore": "탐색할 섹션 선택",
    "Jump to slide": "슬라이드로 이동",
    "End presentation": "프레젠테이션 종료",
}

# 번역 적용
with open('bundle.js', 'r', encoding='utf-8') as f:
    content = f.read()

# 긴 텍스트부터 치환 (부분 매치 방지)
sorted_translations = sorted(translations.items(), key=lambda x: len(x[0]), reverse=True)

for english, korean in sorted_translations:
    # JSON 문자열 이스케이프 처리
    english_escaped = english.replace('"', '\\"').replace('\n', '\\n')
    korean_escaped = korean.replace('"', '\\"').replace('\n', '\\n')
    
    # 문자열 치환
    content = content.replace(f'"{english_escaped}"', f'"{korean_escaped}"')

# 저장
with open('bundle-ko.js', 'w', encoding='utf-8') as f:
    f.write(content)

with open('translations.json', 'w', encoding='utf-8') as f:
    json.dump(translations, f, ensure_ascii=False, indent=2)

print("✅ 완전한 번역 완료!")
print(f"   - 총 {len(translations)}개 항목 번역")
print("   - 출력 파일: bundle-ko.js")
print("   - 번역 매핑: translations.json")
